### ISSUE TITLE
Workbench documentation doesn't match

### ISSUE THREAD

**Issue by stanlemon** [developerforce/SalesforceDurableGenericDemo#2]
The README current reads:

> You can create the channel by using the Workbench and going to Queries > Streaming Push Topics and selecting Generic Subscriptions. Enter the subscription as /u/TestStreaming and click 'Subscribe' (this will create the channel)

However when I use the Workbench I do not see an option for "Generic Subscriptions", nor was I able to figure out where the enter the new subscription. See the attached screen shot.

![screen shot 2016-01-15 at 2 08 56 pm](https://cloud.githubusercontent.com/assets/86314/12362514/bed908bc-bb91-11e5-9a19-89671fc52a4e.png)

**Comment by dcarroll** [comment]
Thought it might be v34 versus v35 issue but it's not.  Turns out you should can find the Generic option at the workbench version here: https://workbench.internal.salesforce.com/streaming.php.

I assume that when Spring 16 is fully released the public instance of workbench will be updated.

**Comment by stanlemon** [comment]
Ah, perfect - I see it now. Thanks!
