### ISSUE TITLE
Generic Streaming without replay

### ISSUE THREAD

**Issue by stomita** [developerforce/SalesforceDurableGenericDemo#4]
It seems that former streaming API endpoint `/cometd/<API_VERSION>` is not working for generic streaming currently (which was working before Spring '16 update). Does it mean all generic streaming subscribers should move their endpoint from `/cometd/<API_VERSION>` to `/cometd/replay/<API_VERSION>` even if they don't use durable streaming ?

**Comment by jthurst01** [comment]
The generic streaming should still continue to work at /cometD/<API_VERSION>.  Can you please send me an email with details on what is not working?  My email is jhurst@salesforce.com

Thanks

**Comment by stomita** [comment]
Sorry this might have been a temporary symptom - now it fixes and messages are broadcasted from both endpoint. Thanks.
